version: '3.7'
services:
    cashmachine-app:
        depends_on: 
            - cashmachine-db
        container_name: cashmachine-app
        volumes: 
            - ./:/go/src/github.com/gfonseca/conductor
        build:
            target: final
            context: ./
            dockerfile: ./Dockerfile
        env_file:
            - ./.env
        ports:
            - "3000:3000"
        links: 
            - "cashmachine-db:cashmachine-db"
    cashmachine-db:
        container_name: cashmachine-db
        image: postgres:13
        ports: 
            - "5432:5432"
        environment:
            POSTGRES_DB: cashmachine
            POSTGRES_PASSWORD: 134689
            POSTGRES_USER: cash_machine
