version: '3.7'
services:
    cashmachine-app:
        container_name: cashmachine-app
        volumes: 
            - ./:/app
        build:
            context: ./
            dockerfile: ./Dockerfile
        env_file:
            - .env
        ports:
            - "3000:3000"
        links: 
            - "cashmachine-db:cashmachine.db"
    cashmachine-db:
        container_name: cashmachine-db
        image: postgres:13
        environment:
            POSTGRES_PASSWORD: 134689
            POSTGRES_USER: cash_machine
            POSTGRES_DB: cashmachine
